Fix to check-in [81162e791f] so that it does not require non-standard modifications to the SQLite "shell.c" source file.
Sorry, but this doesn't work! Compiling this with Makefile.mingw.mistachkin gives:

wbld/shell.o:shell.c:(.text+0x3463): undefined reference to `__imp_win32_access'
wbld/shell.o:shell.c:(.text+0x59ac): undefined reference to `__imp_win32_access'
/usr/lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld: wbld/shell.o: bad reloc address 0x0 in section `.data'
collect2: error: ld returned 1 exit status
win/Makefile.mingw.mistachkin:698: recipe for target 'fossil.exe' failed